# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bandwidth',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CusID', models.CharField(max_length=255, verbose_name='Cus ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Network', models.CharField(max_length=255)),
                ('VLAN', models.CharField(max_length=7, blank=True)),
                ('IXP', models.CharField(max_length=255)),
                ('NIX', models.CharField(max_length=255)),
                ('WEB', models.CharField(max_length=255, blank=True)),
                ('Model', models.CharField(default='?', max_length=255, choices=[('Static-Ring', 'Static-Ring'), ('Static-ISPOther', 'Static-ISPOther'), ('Gre-Server', 'Gre-Server'), ('VirPOP-Static', 'VirPOP-Static'), ('VirPOP-BGP-Static', 'VirPOP-BGP-Static'), ('DynamicBackup-ISPOther-GRE', 'DynamicBackup-ISPOther-GRE'), ('DynamicBackup-ISPOther-VirPOP', 'DynamicBackup-ISPOther-VirPOP'), ('DynamicBackup-Ring-Ring', 'DynamicBackup-Ring-Ring'), ('DynamicBackup-SW-EXT-Ring', 'DynamicBackup-SW-EXT-Ring'), ('DynamicBackup-SW-EXT-VirPop', 'DynamicBackup-SW-EXT-VirPop'), ('Special', 'Special'), ('Transit', 'Transit')])),
                ('CreatedAt', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('LastModified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('Note', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'ordering': ['Name'],
                'verbose_name': 'Customer',
                'verbose_name_plural': ' Summary',
            },
        ),
        migrations.CreateModel(
            name='DynamicBackup_ISPOther_GRE',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CusID', models.CharField(max_length=255, verbose_name='Cus ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Network', models.CharField(max_length=255)),
                ('VLAN', models.CharField(max_length=255, blank=True)),
                ('IXP', models.CharField(max_length=255)),
                ('NIX', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Note', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'ordering': ['Name'],
                'verbose_name': 'DynamicBackup ISPOther GRE Customer',
                'db_table': 'bandwidth_bandwidth',
                'managed': True,
                'verbose_name_plural': 'DynamicBackup ISPOther GRE',
            },
        ),
        migrations.CreateModel(
            name='DynamicBackup_ISPOther_VirPOP',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CusID', models.CharField(max_length=255, verbose_name='Cus ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Network', models.CharField(max_length=255)),
                ('VLAN', models.CharField(max_length=255, blank=True)),
                ('IXP', models.CharField(max_length=255)),
                ('NIX', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Note', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'ordering': ['Name'],
                'verbose_name': 'DynamicBackup ISPOther VirPOP Customer',
                'db_table': 'bandwidth_bandwidth',
                'managed': True,
                'verbose_name_plural': 'DynamicBackup ISPOther VirPOP',
            },
        ),
        migrations.CreateModel(
            name='DynamicBackup_Ring_Ring',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CusID', models.CharField(max_length=255, verbose_name='Cus ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Network', models.CharField(max_length=255)),
                ('VLAN', models.CharField(max_length=255, blank=True)),
                ('IXP', models.CharField(max_length=255)),
                ('NIX', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Note', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'ordering': ['Name'],
                'verbose_name': 'DynamicBackup Ring Ring Customer',
                'db_table': 'bandwidth_bandwidth',
                'managed': True,
                'verbose_name_plural': 'DynamicBackup Ring Ring',
            },
        ),
        migrations.CreateModel(
            name='DynamicBackup_SW_EXT_Ring',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CusID', models.CharField(max_length=255, verbose_name='Cus ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Network', models.CharField(max_length=255)),
                ('VLAN', models.CharField(max_length=255, blank=True)),
                ('IXP', models.CharField(max_length=255)),
                ('NIX', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Note', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'ordering': ['Name'],
                'verbose_name': 'DynamicBackup SW EXT Ring Customer',
                'db_table': 'bandwidth_bandwidth',
                'managed': True,
                'verbose_name_plural': 'DynamicBackup SW EXT Ring',
            },
        ),
        migrations.CreateModel(
            name='DynamicBackup_SW_EXT_VirPop',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CusID', models.CharField(max_length=255, verbose_name='Cus ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Network', models.CharField(max_length=255)),
                ('VLAN', models.CharField(max_length=255, blank=True)),
                ('IXP', models.CharField(max_length=255)),
                ('NIX', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Note', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'ordering': ['Name'],
                'verbose_name': 'DynamicBackup SW EXT VirPop Customer',
                'db_table': 'bandwidth_bandwidth',
                'managed': True,
                'verbose_name_plural': 'DynamicBackup SW EXT VirPop',
            },
        ),
        migrations.CreateModel(
            name='Gre_Server',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CusID', models.CharField(max_length=255, verbose_name='Cus ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Network', models.CharField(max_length=255)),
                ('VLAN', models.CharField(max_length=255, blank=True)),
                ('IXP', models.CharField(max_length=255)),
                ('NIX', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Note', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'ordering': ['Name'],
                'verbose_name': 'Gre Customer',
                'db_table': 'bandwidth_bandwidth',
                'managed': True,
                'verbose_name_plural': 'Gre Server',
            },
        ),
        migrations.CreateModel(
            name='HistoricalBandwidth',
            fields=[
                ('id', models.IntegerField(verbose_name='ID', db_index=True, auto_created=True, blank=True)),
                ('CusID', models.CharField(max_length=255, verbose_name='Cus ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Network', models.CharField(max_length=255)),
                ('VLAN', models.CharField(max_length=7, blank=True)),
                ('IXP', models.CharField(max_length=255)),
                ('NIX', models.CharField(max_length=255)),
                ('WEB', models.CharField(max_length=255, blank=True)),
                ('Model', models.CharField(default='?', max_length=255, choices=[('Static-Ring', 'Static-Ring'), ('Static-ISPOther', 'Static-ISPOther'), ('Gre-Server', 'Gre-Server'), ('VirPOP-Static', 'VirPOP-Static'), ('VirPOP-BGP-Static', 'VirPOP-BGP-Static'), ('DynamicBackup-ISPOther-GRE', 'DynamicBackup-ISPOther-GRE'), ('DynamicBackup-ISPOther-VirPOP', 'DynamicBackup-ISPOther-VirPOP'), ('DynamicBackup-Ring-Ring', 'DynamicBackup-Ring-Ring'), ('DynamicBackup-SW-EXT-Ring', 'DynamicBackup-SW-EXT-Ring'), ('DynamicBackup-SW-EXT-VirPop', 'DynamicBackup-SW-EXT-VirPop'), ('Special', 'Special'), ('Transit', 'Transit')])),
                ('CreatedAt', models.DateTimeField(verbose_name='Created', editable=False, blank=True)),
                ('LastModified', models.DateTimeField(verbose_name='Last Modified', editable=False, blank=True)),
                ('Note', models.CharField(max_length=255, blank=True)),
                ('history_id', models.AutoField(serialize=False, primary_key=True)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(max_length=1, choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')])),
                ('history_user', models.ForeignKey(related_name='+', on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
                'verbose_name': 'historical Customer',
            },
        ),
        migrations.CreateModel(
            name='Special',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CusID', models.CharField(max_length=255, verbose_name='Cus ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Network', models.CharField(max_length=255)),
                ('VLAN', models.CharField(max_length=255, blank=True)),
                ('IXP', models.CharField(max_length=255)),
                ('NIX', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Note', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'ordering': ['Name'],
                'verbose_name': 'Special Customer',
                'db_table': 'bandwidth_bandwidth',
                'managed': True,
                'verbose_name_plural': 'Special',
            },
        ),
        migrations.CreateModel(
            name='Static_ISPOther',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CusID', models.CharField(max_length=255, verbose_name='Cus ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Network', models.CharField(max_length=255)),
                ('VLAN', models.CharField(max_length=255, blank=True)),
                ('IXP', models.CharField(max_length=255)),
                ('NIX', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Note', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'ordering': ['Name'],
                'verbose_name': 'Static ISPOther Customer',
                'db_table': 'bandwidth_bandwidth',
                'managed': True,
                'verbose_name_plural': 'Static ISPOther',
            },
        ),
        migrations.CreateModel(
            name='Static_Ring',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CusID', models.CharField(max_length=255, verbose_name='Cus ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Network', models.CharField(max_length=255)),
                ('VLAN', models.CharField(max_length=255, blank=True)),
                ('IXP', models.CharField(max_length=255)),
                ('NIX', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Note', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'ordering': ['Name'],
                'verbose_name': 'Static Ring Customer',
                'db_table': 'bandwidth_bandwidth',
                'managed': True,
                'verbose_name_plural': 'Static Ring',
            },
        ),
        migrations.CreateModel(
            name='Transit',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CusID', models.CharField(max_length=255, verbose_name='Cus ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Network', models.CharField(max_length=255)),
                ('VLAN', models.CharField(max_length=255, blank=True)),
                ('IXP', models.CharField(max_length=255)),
                ('NIX', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Note', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'ordering': ['Name'],
                'verbose_name': 'Transit Customer',
                'db_table': 'bandwidth_bandwidth',
                'managed': True,
                'verbose_name_plural': 'Transit',
            },
        ),
        migrations.CreateModel(
            name='VirPOP_BGP_Static',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CusID', models.CharField(max_length=255, verbose_name='Cus ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Network', models.CharField(max_length=255)),
                ('VLAN', models.CharField(max_length=255, blank=True)),
                ('IXP', models.CharField(max_length=255)),
                ('NIX', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Note', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'ordering': ['Name'],
                'verbose_name': 'VirPOP BGP Static Customer',
                'db_table': 'bandwidth_bandwidth',
                'managed': True,
                'verbose_name_plural': 'VirPOP BGP Static',
            },
        ),
        migrations.CreateModel(
            name='VirPOP_Static',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('CusID', models.CharField(max_length=255, verbose_name='Cus ID')),
                ('Name', models.CharField(max_length=255, verbose_name='Name')),
                ('Network', models.CharField(max_length=255)),
                ('VLAN', models.CharField(max_length=255, blank=True)),
                ('IXP', models.CharField(max_length=255)),
                ('NIX', models.CharField(max_length=255)),
                ('Model', models.CharField(max_length=255)),
                ('Note', models.CharField(max_length=255, blank=True)),
            ],
            options={
                'ordering': ['Name'],
                'verbose_name': 'VirPOP Static Customer',
                'db_table': 'bandwidth_bandwidth',
                'managed': True,
                'verbose_name_plural': 'VirPOP Static',
            },
        ),
    ]
